volumes:
  book_loan_system_local_postgres_data: { }
  book_loan_system_local_postgres_data_backups: { }
  book_loan_system_local_redis_data: { }

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: book_loan_system_local_django
    container_name: book_loan_system_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: book_loan_system_production_postgres
    container_name: book_loan_system_local_postgres
    volumes:
      - book_loan_system_local_postgres_data:/var/lib/postgresql/data
      - book_loan_system_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: book_loan_system_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:6
    container_name: book_loan_system_local_redis

    volumes:
      - book_loan_system_local_redis_data:/data
    ports:
      - "6379:6379"


  celeryworker:
    <<: *django
    image: book_loan_system_local_celeryworker
    container_name: book_loan_system_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: [ ]
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: book_loan_system_local_celerybeat
    container_name: book_loan_system_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: [ ]
    command: /start-celerybeat

  flower:
    <<: *django
    image: book_loan_system_local_flower
    container_name: book_loan_system_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  pycharm-python:
    <<: *django
    image: book_loan_system_local_python
    container_name: book_loan_system_pycharm_python
    volumes:
      - .:/app:z
    ports:
      - "8001:8001"
    command: python


  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: book_loan_system_local_node
    container_name: book_loan_system_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - '3001:3001'
