# Generated by Django 5.0.10 on 2024-12-09 13:29

import book_loan_system.contrib.utils.model_utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(book_loan_system.contrib.utils.model_utils.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=(book_loan_system.contrib.utils.model_utils.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('authors', models.ManyToManyField(related_name='books', to='books.author')),
                ('genres', models.ManyToManyField(related_name='books', to='books.genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.language')),
            ],
            options={
                'abstract': False,
            },
            bases=(book_loan_system.contrib.utils.model_utils.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField()),
                ('isbn', models.CharField(blank=True, max_length=13, unique=True)),
                ('page_count', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='books.book')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editions', to='books.publisher')),
            ],
            options={
                'abstract': False,
            },
            bases=(book_loan_system.contrib.utils.model_utils.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_date', models.DateField(auto_now_add=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('worn', 'Worn'), ('damaged', 'Damaged')], max_length=50)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='books.edition')),
            ],
            options={
                'abstract': False,
            },
            bases=(book_loan_system.contrib.utils.model_utils.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('on_loan', 'On Loan'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='on_loan', max_length=20)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='books.copy')),
            ],
            options={
                'abstract': False,
            },
            bases=(book_loan_system.contrib.utils.model_utils.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='books.loan')),
            ],
            options={
                'abstract': False,
            },
            bases=(book_loan_system.contrib.utils.model_utils.ReprMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patron_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(book_loan_system.contrib.utils.model_utils.ReprMixin, models.Model),
        ),
        migrations.AddField(
            model_name='loan',
            name='patron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='books.patron'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='books.copy')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='books.patron')),
            ],
        ),
    ]
