# Generated by Django 5.0.10 on 2024-12-10 19:24

import book_loan_system.books.models.loan_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_sample_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=book_loan_system.books.models.loan_models.default_due_date),
        ),
        migrations.AlterField(
            model_name='loanevent',
            name='due_date',
            field=models.DateField(default=book_loan_system.books.models.loan_models.default_due_date),
        ),
        migrations.AlterUniqueTogether(
            name='publisher',
            unique_together={('name', 'country')},
        ),
    ]
