# Generated by Django 5.0.10 on 2024-12-10 21:05

import book_loan_system.books.models.loan_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_loan_due_date_alter_loanevent_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='expiration_date',
            field=models.DateField(default=book_loan_system.books.models.loan_models.default_expiration_date),
        ),
    ]
